# ### Register a participant
# POST http://localhost:5000/api/participants/register
# Content-Type: application/json

# {
#   "name": "Test User",
#   "email": "thesaurabhjaiswar@gmail.com"
# }

# ### Verify participant
# GET http://localhost:5000/api/participants/verify?token=xpgvw0c8p1b&id=6937db73547b9686564fa290


### Run Secret Santa draw
POST http://localhost:5000/api/draw

### Register participant #2
POST http://localhost:5000/api/participants/register
Content-Type: application/json

{
  "name": "User Two",
  "email": "sj49586@gmail.com"
}

### Register participant #3
POST http://localhost:5000/api/participants/register
Content-Type: application/json

{
  "name": "User Three",
  "email": "fy1722attcsc@gmail.com"
}


### Verify participant #2
GET http://localhost:5000/api/participants/verify?token=8g90ypk1g6j&id=6937de08b83aae3bdf3cf5d8
### Verify participant #3
GET http://localhost:5000/api/participants/verify?token=x6vkx31fh29&id=6937de0bb83aae3bdf3cf5dd

### Run Secret Santa draw
POST http://localhost:5000/api/draw
